### ISSUE TITLE
package for webstore

### ISSUE THREAD

**Issue by swanson** [rufuspollock/chrome-csv-viewer#1]
Hi, this script works great - but the link in the readme is to the wrong extension.

Could you package it up for the webstore and update the link?

**Comment by rufuspollock** [comment]
@swanson thanks for reporting this - I did immediately change the URL but could not set it to webstore as had not uploaded yet. I'm about to get this published in the webstore and will close this issue once I have done and corrected the url!

**Comment by swanson** [comment]
@rgrp awesome thanks! My desktop used to be cluttered with `report (6).csv` from testing, but no longer do I have to deal with this pain! :+1:

**Comment by rufuspollock** [comment]
@swanson I've got a first version up here https://chrome.google.com/webstore/detail/recline-csv-viewer/ibfcfelnbfhlbpelldnngdcklnndhael

Could you try installing it and let me know how it works (it should work on local csv files too ...)

**Comment by swanson** [comment]
Error: package is invalid. Details: 'Could not load extension icon 'img/icon-128.png'.'.

**Comment by rufuspollock** [comment]
@swanson new version uploaded (and double-checked by me). Can you check again :-)

**Comment by swanson** [comment]
It installed fine - but doesn't seem to open csv in Chrome on Windows 7. The file just downloads like normal.

**Comment by rufuspollock** [comment]
@swanson have you ticked allow access to file urls in the chrome://extensions section?

**Comment by swanson** [comment]
It wasn't - so I checked it, restarted chrome and same thing.

**Comment by rufuspollock** [comment]
@swanson have you tried an online CSV file? Also any further details of exact steps you take which lead to it just downloading (and does the file name end in .csv)?

**Comment by swanson** [comment]
Yes it was an online CSV. I clicked a link that downloads the file, which was named "monthly_report.csv".

I also tried on Gmail - by exporting my contacts to CSV (Contacts > More > Export... pick CSV). Filename is "google.csv". 

Neither opened with the extension :(

**Comment by rufuspollock** [comment]
@swanson i'm a bit stumped. It's working perfectly for me. Just to check you definitely have the latest version (0.2.0 I think). I also wonder whether you can look into chrome://extensions and have a look at the background_page console and also the console in the main window where you are clicking on the csv link.

BTW please note that if you just paste a csv link into your browser that won't work (the file will download) as the extension currently relies on intercepting click events on csv file links in a given webpage. (Hope to fix this up better soon)

**Comment by swanson** [comment]
Uninstall, reinstalled and it started working, weird!

Thanks!
